### PR TITLE
fix: Black screenn when press back button

### PR DESCRIPTION
**Pull request by tensionc**
https://github.com/hiddify/hiddify-next/issues/1255

### CODE REVIEW

**Comment by tensionc** [comment]
Delete desktop arrow display

**Comment by tensionc** [comment]
Ensure that the return of other pages is not affected

**Comment by hiddify-com** [comment]
It make issues on mobile devices

**Comment by tensionc** [comment]
> 它会在移动设备上产生问题

我想知道在那个页面产生错误，我现在无法复现错误

**Comment by netsupcloud** [comment]
> It make issues on mobile devices

i have it on windows only

**Pull request merged**
