### PR TITLE
feat: Use dark tray icon in light theme

### PR DESCRIPTION
**Pull request by sky96111**
The original white tray icon is visually inappropriate in Windows Light theme.
I made a reversed color variant for Light theme.
https://github.com/hiddify/hiddify-next/issues/620

### CODE REVIEW

**Comment by hiddify-com** [comment]
Great thanks

Would you please also change the color to green when connected?

**Comment by sky96111** [comment]
I'll give it a try, though I'm not familiar with riverpod.
By the way, I also see ``tray_icon_connected.ico`` and ``tray_icon_disconnected.ico`` but no PNG. Is this to show connection status for windows only?
While, I think red tray_icon_disconnected is not a good idea. The color red attracts the user's attention and indicates a state of emergency, but leave a disconnected proxy app in background should be a very normal occurrence.

**Comment by hiddify-com** [comment]
yes i agree to not use disconnected.ico but tray icon connected is useful. it is needed for windows macos and linux 
if png is needed, would you please convert it to png?

**Comment by sky96111** [comment]
ok, I found *.png in source folder. I'll try connected status icon when available.

**Comment by suhai332** [comment]
十分期待此次提交合并，这个十分重要！

**Comment by hiddify-com** [comment]
It seems that there is an issue in the color of tray icon in linux

**Comment by someonemax** [comment]
> It seems that there is an issue in the color of tray icon in linux

Yes
I detailed the issue and my suggested solution here: https://github.com/hiddify/hiddify-next/issues/620#issuecomment-2014127287

**Pull request merged**
